name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.9]

    steps:
      - uses: actions/checkout@b56e6a3d768b11aef1d4c73977caf6413c0d74c8 # v3.2.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # ratchet:actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show help
        run: |
          python src/SPDXMerge.py --help

      - name: Run pylint
        run: |
          pip install -r requirements-dev.txt
          pylint **/*.py

      - name: Run pytest 
        run: |
          pytest .
